// Authentication actions
export const GET_ERRORS = "GET_ERRORS";
export const DEV_LOADING = "DEV_LOADING";
export const SET_CURRENT_DEV = "SET_CURRENT_DEV";

// Jirastories actions
export const CREATE_JIRASTORY = "CREATE_JIRASTORY";
export const UPDATE_JIRASTORY = "UPDATE_JIRASTORY";
export const DELETE_JIRASTORY = "DELETE_JIRASTORY";
export const GET_JIRASTORY = "GET_JIRASTORY";
export const JIRASTORY_LOADING = "JIRASTORY_LOADING";
export const GET_JIRASTORIES = "GET_JIRASTORIES";
export const JIRASTORIES_LOADING = "JIRASTORIES_LOADING";
